### ISSUE TITLE
instructions for getting inference for fatigue detection for a new video

### ISSUE THREAD

**Issue by monajalal** [Pe4enIks/Fatigue-Detection#1]
Great job. Are you please able to provide instruction for how to detect fatigue on a new video for inference?
Thank you

**Comment by epishchik** [comment]
Hi! Thank you very much. I'll try to write a README and inference_fatigue.py soon, when I have enough time. 

Now you can try using inference_algo.py (you can try inference_cnn.py, but it works worse), you can set some parameters in config_algo.yaml.

In general, you can use the statistics "frequencies", "durations", "ears" and "aecd" to define one or more binary thresholds. It wasn't defined in this code, but I used two binary thresholds with "OR" condition, I calculated the thresholds as an average over several videos where I was tired and not.
